### ISSUE TITLE
Botón volver

### ISSUE THREAD

**Issue by marcbria** [libreqda/libreQDA#30]
Traslado desde el github de tryolabs al del proyecto:
https://github.com/tryolabs/libreQDA/issues/23

Juan resume:

El "problema" es que al entrar en la pantalla de creación de códigos, lo que ocurre es que se abre una nueva pestaña del navegador. Cerrando esa pestaña volvemos a encontrarnos con el documento. Creo que lo más conveniente sería que estas nuevas pestañas en realidad fueran ventanas emergentes.

**Comment by jmunoz298** [comment]
Duplicado o muy similar a: 
[https://github.com/libreqda/libreQDA/issues/21](https://github.com/libreqda/libreQDA/issues/21)
