### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by trenkert** [libreqda/libreQDA#39]
If not, could you provide an English translation?

**Comment by lupa18** [comment]
It's quite dead, Tryolabs didn't complete their work and the software it's not finished, and
is not fully functional. LQDA doesn't fill our expectations, so we consider it unusable at the moment.

If you want to write to whole team with proposals or things like that, you can do it here:
libreqda@listas.softwarelibre.edu.uy

**Comment by joseluizn** [comment]
> 
> 
> I'm really trying to get this migration done by 2020 deadline for legacy python and it won't be too fancy: just a one to one migration. Once I get it building in Python3 and Django 2.1+, I'll start adding features noted in the issues backlog.

Joe I'm interested in using this library as part of my master's thesis, I wanted to know if you have any code you could share? I'm currently trying to install it but facing a lot of issues on my first try.
